### ISSUE TITLE
[BUG] Tags disappear on some event

### ISSUE THREAD

**Issue by Darkenlord1** [starik222/BooruDatasetTagManager#104]
Don't know for sure why, but most tags disappear from random images, only remaining ones are those which was added through "add tag to all".

Got like 4 of those occurred in my dataset out of ~600 pairs.

Guess that didn't happen on previous versions (like < 2.0.0).
Currently using this release - [e80208a81122d5a6bed9d1215fe7e5d8c3018c58](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.2) (2.0.2)

**Comment by jojje** [comment]
Yes, I've noticed that bug as well. It will seemingly wipe all tags from the affected random image. Only during training did I notice some images had blank caption files. For now I've created a "cron-job" that automatically backs up all the tags in the current workspace folder, so that I'll suffer minimal data loss. Have yet to discover some pattern that triggers this data corruption (destruction), so can't really offer any additional details other than to confirm this happens randomly to me as well.

**Comment by starik222** [comment]
Version [2.1.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.1) adds an additional check of saved data that may help find the source of the problem. If the tags do not disappear from the program itself (visible in the tags table), then this check will show an error and generate debugging data.

**Comment by catmanc** [comment]
[ErrorData.json](https://github.com/starik222/BooruDatasetTagManager/files/14381212/ErrorData.json)

I have the same problem in both 2.1.1 and 2.1.2

**Comment by starik222** [comment]
> [ErrorData.json](https://github.com/starik222/BooruDatasetTagManager/files/14381212/ErrorData.json)
> 
> I have the same problem in both 2.1.1 and 2.1.2

Thank you, this is an error in the verification algorithm itself, when, due to the difference in the ' ' and '_' characters, the verification led to a false error. Fixed in [2.1.3](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.3)

**Comment by catmanc** [comment]
> Thank you, this is an error in the verification algorithm itself, when, due to the difference in the ' ' and '_' characters, the verification led to a false error. Fixed in [2.1.3](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.3)

Thank you for your quick response, but still got the same issue...
[ErrorData.json](https://github.com/starik222/BooruDatasetTagManager/files/14399102/ErrorData.json)

**Comment by jojje** [comment]
Yes, same here. However I've failed to detect the precise point at which the tags were deleted, so don't have an ErrorData to share that captures the specific event. The data loss is typically discovered much later, either when I _happen_ to scroll by an image that now have zero tags, or when I've accidentally saved the work, causing the caption files to be updated on disk and discovering some of them are zero bytes in size.

I'll create a directory scanner for zero-byte files, so I'm alerted directly when this problem occurs. Unfortunately that means I'll have to "CTRL+S" after each UI interaction as otherwise what's captured in the ErrorData file will be some _other_ operation overwriting the actual event that caused the bug.

**Comment by Darkenlord1** [comment]
Looks like it just removed tags on image when i replaced tag in all images. 
Btw, where i can get the ErrorData log?

**Comment by starik222** [comment]
> Looks like it just removed tags on image when i replaced tag in all images. Btw, where i can get the ErrorData log?
> 
> Using this release [25da3b3](https://github.com/starik222/BooruDatasetTagManager/commit/25da3b318efb6378eb61bc1b008bcc63c0ed52dd) (v2.1.4)

Did you get an error message when saving? ErrorData.json is generated only when an error occurs and is located in the program folder.

**Comment by Darkenlord1** [comment]
> > Looks like it just removed tags on image when i replaced tag in all images. Btw, where i can get the ErrorData log?
> > Using this release [25da3b3](https://github.com/starik222/BooruDatasetTagManager/commit/25da3b318efb6378eb61bc1b008bcc63c0ed52dd) (v2.1.4)
> 
> Did you get an error message when saving? ErrorData.json is generated only when an error occurs and is located in the program folder.

Apparently i didnt save the changes, simply opened the image in folder and replaced tags back from file. Will try next time. Ty for response.

**Comment by starik222** [comment]
Fixed in [2.1.5](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.5)
