### ISSUE TITLE
The tool has an abnormal image rotation during use

### ISSUE THREAD

**Issue by huangjianyi0701** [starik222/BooruDatasetTagManager#157]
The tool has an abnormal image rotation during use
![image](https://github.com/user-attachments/assets/696a1e4f-f941-4ce9-8d9e-07d9be29e225)
The original images are all normal in the preview and image viewer
![image](https://github.com/user-attachments/assets/ef96a3ba-6dd6-48e0-8a89-18e205f6cf20)

**Comment by starik222** [comment]
I can assume that the problem is in your images. I have seen images that were displayed normally in some programs, but were rotated in others. I don't know what this is connected with, but when resaving such images to another format and back, the problem disappeared. You can also attach an archive with some images so that I can check it.
