### ISSUE TITLE
[Request] Allow to control images table presentation

### ISSUE THREAD

**Issue by pastuh** [starik222/BooruDatasetTagManager#36]
Currently, the table loads all information in a fixed position.
Allow to adjust dimensions or even hide specific columns.

Example:
Expand or reduce the "Image" a little more (so you don't need to use the "preview image" function)
Hide columns "File path", "Change time" (after that could be only one or two visible columns)

**Comment by jojje** [comment]
Being able to hide the filename and change time would be an improvement indeed, as I use keyboard as much as I can and for some reason when navigating to the image list, the chosen cell tends to settle on filename, which scrolls the image thumbnail out of view. It's a minor annoyance, one I can live with, but it would be great if we could disable the fields we're not interested in.

**Comment by starik222** [comment]
Setting up the displayed columns is implemented in version [2.1.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.1). The width of the image column can only be changed through the settings window, and cannot be changed dynamically, since the size of the images changes when the dataset is loaded.
